CREATE TABLE `tbl_application` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `applicantId` bigint(20) unsigned NOT NULL,
  `applicantJobNum` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '候选人工号',
  `applicantName` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '候选人姓名',
  `applicantMobile` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '候选人电话',
  `applicantGender` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '候选人性别',
  `applicantBirthday` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '候选人出生年月',
  `applicantProWork` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '候选人专业技术职务',
  `applicantHiredate` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '候选人来院时间',
  `deptName` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '科室名称',
  `declarationYear` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '申报年度',
  `applyTime` datetime DEFAULT NULL COMMENT '填表时间',
  `major` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '主要专业领域及研究方向',
  `intro` text COLLATE utf8mb4_unicode_ci COMMENT '个人代表性成就简介',
  `state` tinyint(3) unsigned NOT NULL DEFAULT '1' COMMENT '状态：1 待提交 2 审核中 3 待重新提交 4 重新审核 5 审核通过 6 审批通过',
  `level` tinyint(3) unsigned NOT NULL COMMENT '层级：1 临床新技术新业务学习 2 高水平科学研究 3 高水平学术会议交流',
  `groupAdvice` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '小组意见',
  `updatedAt` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `createdAt` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `groupName` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '审核小组名称',
  `lxzy` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '留学专业',
  `ywmc` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '新技术新业务名称',
  `xxlr` varchar(1000) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '学习内容介绍',
  `xxgh` varchar(1000) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '学习内容的先进性、可行性，学习规划',
  `lxgj` varchar(45) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '留学国家',
  `lxxx` varchar(45) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '留学学校',
  `xxpm` varchar(45) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '学校世界排名',
  `zypm` varchar(45) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '专业世界排名',
  `dsxm` varchar(45) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '导师姓名',
  `xsrz` varchar(45) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '学术影响及\n学术任职\n',
  `xzzw` varchar(45) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '行政职务',
  `dsyq` tinyint(4) DEFAULT '0' COMMENT '是否有该导师正式邀请信',
  `dsjj` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '导\n师\n简\n介\n',
  `tjjs` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '导师提供留学条件介绍',
  `hymczw` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '会议名称中文',
  `hymcyw` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '会议名称英文',
  `hykssj` varchar(45) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '会议日期开始时间',
  `hyjssj` varchar(45) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '会议日期结束时间',
  `hyzbf` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '会议主办方',
  `hydd` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '会议地点',
  `hyjj` varchar(1000) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '会议简介',
  `hyzx` varchar(45) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '主席',
  `hyzxzx` varchar(45) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '执行主席',
  `hyzcr` varchar(45) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '主持人',
  `hybg` varchar(45) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '口头报告',
  `hylr` varchar(1000) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '拟提交会议交流内容',
  `dddz` tinyint(1) DEFAULT '0' COMMENT '是否单独带组',
  `dzsj` varchar(45) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '开始带组时间',
  `zygjc` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '从事专业关键词',
  `ylkh` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '近5年医疗考核情况',
  `lxkssj` varchar(45) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '申请留学开始时间',
  `lxjssj` varchar(45) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '申请留学结束时间',
  `grjj` varchar(1000) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '个人简历',
  `cjjj` varchar(1000) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '主要成就简介',
  `lxfx` varchar(45) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '留学方向',
  `khzb` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '预期成果及量化考核指标\n',
  `bysj` varchar(45) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '毕业时间',
  `zycj` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '主要成就简介',
  `zyzw` varchar(45) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '现任专业技术职务',
  `ksfzr` varchar(45) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '科室负责人',
  `stage` tinyint(4) DEFAULT '0' COMMENT '流程阶段',
  `dsxzzw` varchar(45) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '行政职务',
  `school` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '学校',
  `education` varchar(45) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '学位',
  `sfcj` tinyint(4) DEFAULT NULL COMMENT '是否同意申请办理因公护照出国',
  `pzkssj` varchar(45) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '批准开始时间',
  `pzjssj` varchar(45) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '批准结束时间',
  `xxjjpm` varchar(45) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '学校NIH基金申请总额排名',
  `yyxz` varchar(45) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '1.大学或研究所附属医院',
  `yypm` varchar(45) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '医院综合排名',
  `yyjjpm` varchar(45) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '医院年度NIH基金申请总额排名',
  `zyxgx` varchar(45) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '与申请人所从事专业的相关性',
  `dsjq` tinyint(4) DEFAULT NULL COMMENT '导师为海外杰青',
  `dsqr` tinyint(4) DEFAULT NULL COMMENT '千人计划B类',
  `dswjys` tinyint(4) DEFAULT NULL COMMENT '中国科学院或工程院外籍院士',
  `dsys` tinyint(4) DEFAULT NULL COMMENT '导师为该国科学院院士',
  `dszx` tinyint(4) DEFAULT NULL COMMENT '导师为本专业该国一级学会或世界一级学会主席',
  `zyfg` tinyint(4) DEFAULT NULL COMMENT '副高级以上专业技术职务',
  `zyzj` tinyint(4) DEFAULT NULL COMMENT '中级专业技术职务',
  `zy8n` tinyint(4) DEFAULT NULL COMMENT '申请人在我院连续工作满8年及以上',
  `zy5n` tinyint(4) DEFAULT NULL COMMENT '申请人在我院连续工作满5年以上8年以下',
  `xkzd` tinyint(4) DEFAULT NULL COMMENT '国家重点学科',
  `xklczd` tinyint(4) DEFAULT NULL COMMENT '国家临床重点专科',
  `xksjzd` tinyint(4) DEFAULT NULL COMMENT '省级重点专科',
  `xxzhpm` varchar(45) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '学校综合排名',
  `zyzhpm` varchar(45) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '专业排名',
  `zychj` tinyint(4) DEFAULT NULL COMMENT '初级专业技术职务',
  `score` int(11) DEFAULT NULL COMMENT '综合评分',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
