CREATE TABLE `tbl_review` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `applicationId` bigint(20) unsigned NOT NULL,
  `reviewerId` bigint(20) unsigned NOT NULL,
  `reviewerName` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '审核人',
  `reviewState` tinyint(4) NOT NULL DEFAULT '0' COMMENT '审核状态：0 未审核 1 驳回 2 通过',
  `reviewAdvice` varchar(2000) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '审核意见',
  `isRejected` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否被驳回',
  `rejectReason` varchar(2000) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '驳回原因',
  `reviewTime` datetime DEFAULT NULL COMMENT '审核时间',
  `updatedAt` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `createdAt` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `rejectedBy` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '驳回人',
  `stage` int(11) DEFAULT NULL COMMENT '阶段',
  `sfxj` tinyint(4) DEFAULT NULL COMMENT '是否先进',
  `sftj` tinyint(4) DEFAULT NULL COMMENT '是否推荐',
  `ywcyj` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '科室意见',
  `ywcyj1` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '科室意见',
  `ywcyj2` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '科室意见',
  `ywcyj3` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '科室意见',
  `ywcyj4` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '科室意见',
  `ywcyj5` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '科室意见',
  `sfcj` tinyint(4) DEFAULT NULL COMMENT '是否参加',
  `pzkssj` varchar(45) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '批准开始时间',
  `pzjssj` varchar(45) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '配准结束时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uni_application_id_user_id` (`applicationId`,`reviewerId`)
) ENGINE=InnoDB AUTO_INCREMENT=107 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
