CREATE TABLE `tbl_user` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `jobNum` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '工号',
  `name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '姓名',
  `deptDesc` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '部门描述',
  `position` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '职位',
  `hrId` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '人事编号',
  `gender` tinyint(1) unsigned DEFAULT NULL COMMENT '姓名 0 女 1 男',
  `birthday` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '出生年月',
  `workerGroup` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '员工组',
  `idCard` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '身份证',
  `idType` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '身份类别',
  `title` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '职称',
  `education` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '学历',
  `school` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '毕业院校',
  `birthplace` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '籍贯',
  `nation` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '籍贯',
  `politics` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '政治面貌',
  `hiredate` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '入职日期',
  `workdate` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '参加工作时间',
  `proWork` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '专业技术职务',
  `password` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `mobile` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '手机号码',
  `role` tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT '用户角色 0 普通用户 21 党委办公室 22 纪委办公室 23 宣传部 24 第一临床学院 25 研究生管理办公室 50 人才工作领导小组',
  `createdAt` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `bysj` varchar(45) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '毕业时间',
  `ksfzrxm` varchar(45) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '科室负责人姓名',
  `ksfzrgh` varchar(45) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '科室负责人工号',
  `zyzw` varchar(45) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '专业技术职务',
  `ksfzrzw` varchar(45) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '科室负责人职务',
  `xzzw` varchar(45) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '行政职务',
  PRIMARY KEY (`id`),
  UNIQUE KEY `jobNum` (`jobNum`)
) ENGINE=InnoDB AUTO_INCREMENT=21101 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
