version: '3'
services:
  flyway:
    image: boxfuse/flyway:5.1-alpine
    command: -url=jdbc:mysql://db -schemas=declare -user=root -password=DYHGujh09RKyIdRR migrate
    volumes:
      - ./migrations:/flyway/sql
    depends_on:
      - db
      - redis
  db:
    image: mysql:5.7
    restart: always
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      - MYSQL_ROOT_PASSWORD=DYHGujh09RKyIdRR
    volumes:
      - ./db/mysql:/var/lib/mysql
    ports:
      - 3306:3306
  redis:
    image: redis:3.2-alpine
    restart: always
    command: redis-server --appendonly yes
    volumes:
      - ./db/redis:/data
    ports:
      - 6379:6379

